---
name: "Build Bioc Containers with TinyTex"

on:
  push:
    branches:
      - docker-builder
  workflow_dispatch:


jobs:
  build-containers:
    name: Build Container
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
        - { platform: linux/arm64, tag: devel-arm64 }
        - { platform: linux/amd64, tag: devel-amd64 }
    
    steps: 
    
    - uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ matrix.config.platform }}
        push: true
        tags: ghcr.io/${{ github.actor }}/bioc-with-tinytex:devel-${{ matrix.config.tag }}
