name: test build deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-arm64:
    name: Test package on ARM64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          base_image: bioconductor/bioconductor:RELEASE_3_16
          
          run: |
            uname -a
            git clone https://github.com/grimbough/Rhdf5lib.git
            R CMD build Rhdf5lib
