name: test build deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-arm64:
    name: Test package on ARM64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64v8

      - name: Test package
        uses: grimbough/arm64-workflow/.github/workflows/check.yml@main
        with:
          repository: grimbough/Rhdf5lib
