name: test build deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    
    steps:
      
      - name: Clone package to be tested
        run: |
          git clone https://github.com/grimbough/rhdf5.git
          cd rhdf5
          git checkout h5s_unlimited

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R-lib

      - name: Install Dependencies
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          install: |
            mkdir -p /build /tmp/R-lib
            echo "options(Ncpus=2L, timeout = 300)" >> ~/.Rprofile

          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
            
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
            
          run: |
            uname -m
            env
            Rscript -e "library(remotes)" -e "dev_package_deps(Sys.getenv('PKG'), dependencies = TRUE) |> update(upgrade = 'always')"
            
  check-arm64:
    needs: install-dependenceies
    name: Test package on ARM64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Clone package to be tested
        run: |
          git clone https://github.com/grimbough/rhdf5.git
          cd rhdf5
          git checkout h5s_unlimited
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Load Cached Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R-lib
        
      - name: Install Package
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
          
          run: |  
            Rscript -e "options('Ncpus')"
            R CMD INSTALL ${PKG} &> ${PKG}.install-out.txt
            cat ${PKG}.install-out.txt
            
      - name: Build & Check Package
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          install: |
            Rscript -e "install.packages('tinytex')" \
              -e "tinytex::install_tinytex(extra_packages = c(
                'bera', 'caption', 'changepage', 'enumitem', 'fancyhdr', 
                'footmisc', 'marginfix', 'mathtools', 'nowidow', 'parnotes', 
                'parskip', 'placeins', 'ragged2e', 'soul', 'titlesec', 'xstring',
                'preprint', 'courier'
              ))"

          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
          
          run: |
            ## pdflatex isn't on the PATH unless we set this
            PATH=~/bin/:${PATH}
            R CMD build --keep-empty-dirs --no-resave-data ${PKG}
            R CMD check --install=check:${PKG}.install-out.txt --library="${R_LIBS_USER}" --no-vignettes --timings ${PKG}*.tar.gz
            mkdir -p ${PKG}.buildbin-libdir
            R CMD INSTALL --build --library=${PKG}.buildbin-libdir ${PKG}*.tar.gz
            
      - name: What's here?
        run: |
          echo "$PWD"
          ls -lh ${PWD}
          echo "${{ runner.temp }}/R-lib"
          ls -l ${{ runner.temp }}/R-lib
          echo ${{ github.workspace }}
            
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: |
            ${{ github.workspace }}/*.tar.gz
            ${{ github.workspace }}/*.install-out.txt
            ${{ github.workspace }}/*.Rcheck
          if-no-files-found: warn
  
