name: test build deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-arm64:
    name: Test package on ARM64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          #base_image: arm64v8/r-base
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ github.token }}
          
          install: |
            echo "options(Ncpus=2L, timeout = 300)" >> ~/.Rprofile

          
          run: |
            uname -m
            export R_LIBS_USER=/tmp/R-lib
            mkdir -p ${R_LIBS_USER}
            env
            git clone https://github.com/grimbough/Rhdf5lib.git
            Rscript -e "library(remotes)" -e "dev_package_deps('Rhdf5lib', dependencies = TRUE) |> update(upgrade = 'always')"
            PKG=Rhdf5lib
            R CMD INSTALL ${PKG} &> ${PKG}.install-out.txt
            cat ${PKG}.install-out.txt
            R CMD build --keep-empty-dirs --no-resave-data ${PKG}
            R CMD check --install=check:${PKG}.install-out.txt --library="${R_LIBS_USER}" --no-vignettes --timings "${PKG}*.tar.gz"
