name: test build deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-arm64:
    name: Test package on ARM64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: bioconductor/bioconductor:RELEASE_3_16@b1567beb88ec8efc0e489abf553b0238ccdf7503c2a815a9bff183dc6be7138b
          githubToken: ${{ github.token }}
          run: |
            uname -m
            env
            git clone https://github.com/grimbough/Rhdf5lib.git
            Rscript -e "install.packages('BiocStyle')"
            R CMD build Rhdf5lib
