name: Testing package on arm64

on:
  push:
  workflow_dispatch:
  
env:
  PKG: 'rhdf5filters'

jobs:
  install-depdendencies:
    name: Install package dependencies
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-
            
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            --volume ${{ runner.temp }}/R-lib:/R-lib
            --volume ${{ github.workspace }}:/build
            --env R_LIBS_USER=/R-lib
          run: |
            echo "options(Ncpus=2L, timeout = 300)" >> ~/.Rprofile
            Rscript -e "pkgs <- remotes::dev_package_deps('/build/examplePKG', dependencies = TRUE)" -e "pkgs" -e "pkgs$package[pkgs$diff > 1 | pkgs$diff < 0]" -e "BiocManager::install(pkgs$package[pkgs$diff > 1 | pkgs$diff < 0], update = TRUE, ask = FALSE)"
            
  check-arm64:
    name: Test package on ARM64
    runs-on: ubuntu-22.04
    needs:   install-depdendencies
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-

      - name: R CMD INSTALL
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            --volume ${{ runner.temp }}/R-lib:/R-lib
            --volume ${{ github.workspace }}:/build
            --env R_LIBS_USER=/R-lib
            --workdir /build
          run: |
            R CMD INSTALL examplePKG &> examplePKG.install-out.txt
            cat examplePKG.install-out.txt
            R CMD build --keep-empty-dirs --no-resave-data examplePKG
            R CMD check --install=check:examplePKG.install-out.txt --library="${R_LIBS_USER}" --no-vignettes --timings examplePKG*.tar.gz
            mkdir -p ${PKG}.buildbin-libdir
            R CMD INSTALL --build --library=${PKG}.buildbin-libdir ${PKG}*.tar.gz
            exit 1;
          shell: bash

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: |
            ~/**/*.tar.gz
            ~/**/*.install-out.txt
            ~/**/*.Rcheck
          if-no-files-found: warn
          
